server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/basketservice
    username: basketservice
    password: security
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      # Set for testing purposes. Should be: validate or update
      ddl-auto: create-drop